In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('../Datasets/Flavors.csv')
data.head(3)

,Flavor,Base Flavor,Liked,Flavor Rating,Texture Rating,Total Rating
0,Mint Chocolate Chip,Vanilla,Yes,10.0,8.0,18.0
1,Chocolate,Chocolate,Yes,8.8,7.6,16.6
2,Vanilla,Vanilla,No,4.7,5.0,9.7

### Filtering by one Column

In [3]:
data[data['Liked'] == 'Yes']

,Flavor,Base Flavor,Liked,Flavor Rating,Texture Rating,Total Rating
0,Mint Chocolate Chip,Vanilla,Yes,10.0,8.0,18.0
1,Chocolate,Chocolate,Yes,8.8,7.6,16.6
3,Cookie Dough,Vanilla,Yes,6.9,6.5,13.4
4,Rocky Road,Chocolate,Yes,8.2,7.0,15.2
6,Cake Batter,Vanilla,Yes,6.5,6.0,12.5
8,Chocolte Fudge Brownie,Chocolate,Yes,8.2,7.1,15.3

##### Multiple condition filering

In [4]:
data.dtypes

data[(data['Liked'] == 'Yes') & (data['Flavor Rating'] > 8.5)]

,Flavor,Base Flavor,Liked,Flavor Rating,Texture Rating,Total Rating
0,Mint Chocolate Chip,Vanilla,Yes,10.0,8.0,18.0
1,Chocolate,Chocolate,Yes,8.8,7.6,16.6

### Conditional Column

1. ✅ Using apply() with lambda

In [18]:
conditional_col = data['Total Rating'].apply(lambda x: 'Great' if x > 8 else 'Not Great')
print(type(conditional_col))
print(conditional_col)

<class 'pandas.core.series.Series'>
0        Great
1        Great
2        Great
3        Great
4        Great
5    Not Great
6        Great
7        Great
8        Great
Name: Total Rating, dtype: object

2. 🧱 Using np.where()

In [22]:
import numpy as np
data['status'] = np.where(data['Total Rating'] >= 20, 'pass', 'fail')

3. 📌 Using np.select() for multiple conditions

In [23]:

conditions = [data['Total Rating'] <= 20, data['Total Rating'] >= 20]
choices = ['A', 'B']
data['grade'] = np.select(conditions, choices, default='F')

4. 🧠 Using pd.cut() for binning

In [21]:
data['Conditional Col'] = pd.cut(data['Total Rating'], bins=[0,6,8,100], labels=['F','B','A'])  # Bin scores into grades
print(data)

                   Flavor Base Flavor Liked  Flavor Rating  Texture Rating  \
0     Mint Chocolate Chip     Vanilla   Yes           10.0             8.0
1               Chocolate   Chocolate   Yes            8.8             7.6
2                 Vanilla     Vanilla    No            4.7             5.0
3            Cookie Dough     Vanilla   Yes            6.9             6.5
4              Rocky Road   Chocolate   Yes            8.2             7.0
5               Pistachio     Vanilla    No            2.3             3.4
6             Cake Batter     Vanilla   Yes            6.5             6.0
7              Neapolitan     Vanilla    No            3.8             5.0
8  Chocolte Fudge Brownie   Chocolate   Yes            8.2             7.1

   Total Rating Conditional Col
0          18.0               A
1          16.6               A
2           9.7               A
3          13.4               A
4          15.2               A
5           5.7               F
6          12.5               A
7           8.8               A
8          15.3               A

5. ⚙️ Using .loc[] for conditional assignment

* Explanation: More readable for multiple conditions or when assigning in steps.

In [24]:
data.loc[data['Total Rating'] >= 50, 'status'] = 'pass'
data.loc[data['Total Rating'] < 50, 'status'] = 'fail'

7. 🧪 Using .map() with a dict (for categorical conditions)

* Explanation: Replace categorical codes with labels.

In [37]:
data['status 2'] = data['status'].map({'pass' : 'P', 'fail': 'F'})

print(data['status 2'])

0    F
1    F
2    F
3    F
4    F
5    F
6    F
7    F
8    F
Name: status 2, dtype: object

✅ 1. Using np.select() for Range Mapping

* ✔️ Best for: Multiple ranges, clear and fast.

In [33]:
import numpy as np

conditions = [
    (data['Total Rating'] < 50),
    (data['Total Rating'] >= 50) & (data['Total Rating'] < 80),
    (data['Total Rating'] >= 80)
]
choices = ['Low', 'Medium', 'High']

data['score_level'] = np.select(conditions, choices, default='Unknown')

print(data)

                   Flavor Base Flavor Liked  Flavor Rating  Texture Rating  \
0     Mint Chocolate Chip     Vanilla   Yes           10.0             8.0
1               Chocolate   Chocolate   Yes            8.8             7.6
2                 Vanilla     Vanilla    No            4.7             5.0
3            Cookie Dough     Vanilla   Yes            6.9             6.5
4              Rocky Road   Chocolate   Yes            8.2             7.0
5               Pistachio     Vanilla    No            2.3             3.4
6             Cake Batter     Vanilla   Yes            6.5             6.0
7              Neapolitan     Vanilla    No            3.8             5.0
8  Chocolte Fudge Brownie   Chocolate   Yes            8.2             7.1

   Total Rating Conditional Col status grade status 2 score_level
0          18.0               A   fail     A      NaN         Low
1          16.6               A   fail     A      NaN         Low
2           9.7               A   fail     A      NaN         Low
3          13.4               A   fail     A      NaN         Low
4          15.2               A   fail     A      NaN         Low
5           5.7               F   fail     A      NaN         Low
6          12.5               A   fail     A      NaN         Low
7           8.8               A   fail     A      NaN         Low
8          15.3               A   fail     A      NaN         Low