### **Sorting Assignment**

In [1]:
import pandas as pd
import numpy as np

#### **Part 1: Explore columns**


Print all column names in the dataframe.

In [2]:
df = pd.read_csv('../../Data/Tokyo 2021 dataset v3.csv')
df.columns

Index(['Rank', 'Team/NOC', 'Gold Medal', 'Silver Medal', 'Bronze Medal',
       'Total', 'Rank by Total', 'NOCCode', 'Continent'],
      dtype='object')

Sort the column names alphabetically (A → Z).

In [3]:
sorted(df.columns)

['Bronze Medal',
 'Continent',
 'Gold Medal',
 'NOCCode',
 'Rank',
 'Rank by Total',
 'Silver Medal',
 'Team/NOC',
 'Total']

Sort the column names reverse alphabetically (Z → A).

In [10]:
sorted(df.columns,reverse=True)
df = df.sort_index(axis=1,ascending=False)
print(df.columns)

Index(['Total', 'Team/NOC', 'Silver Medal', 'Rank by Total', 'Rank', 'NOCCode',
       'Gold Medal', 'Continent', 'Bronze Medal'],
      dtype='object')

Find how many columns contain the word "Total" (case-insensitive).

In [11]:
total_cols = [c for c in df.columns if "Total" in c]
total_cols = [c for c in df.columns if "total" in c.lower()]

total_cols

['Total', 'Rank by Total']

Create a list of column names that contain "Gold", "Silver", or "Bronze".

In [13]:
medal_cols = [c for c in df.columns if any(m in c for m in ["Gold", "Silver", "Bronze"])]
df[medal_cols].head(5)

   Silver Medal  Gold Medal  Bronze Medal
0            41          39            33
1            32          38            18
2            14          27            17
3            21          22            22
4            28          20            23

In [ ]:
medal_cols = list(
    filter(lambda c: any(m in c for m in ["Gold", "Silver", "Bronze"]), df.columns)
)

#### **Part 2: Sort rows by a single column**


Sort the dataframe by Country (or equivalent country column) in ascending order.

In [14]:
df.sort_values('Continent', axis=0)

,Total,Team/NOC,Silver Medal,Rank by Total,Rank,NOCCode,Gold Medal,Continent,Bronze Medal
55,4,Ethiopia,1,47,56,ETH,1,Africa,2
51,3,South Africa,2,60,52,RSA,1,Africa,0
87,1,Côte d'Ivoire,0,77,86,CIV,0,Africa,1
57,2,Tunisia,1,66,58,TUN,1,Africa,0
88,1,Ghana,0,77,86,GHA,0,Africa,1
...,...,...,...,...,...,...,...,...,...
65,5,Colombia,4,42,66,COL,0,South America,1
37,3,Ecuador,1,60,38,ECU,2,South America,0
11,21,Brazil,6,12,12,BRA,7,South America,8
71,3,Argentina,1,60,72,ARG,0,South America,2
46,4,Venezuela,3,47,46,VEN,1,South America,0

Sort the dataframe by Total medals in descending order.

In [ ]:
df.sort_values('Total', axis=0, ascending=False)

Sort the dataframe by Gold medals first, then check the top 10 rows.

In [ ]:
df = df.sort_values('Gold Medal', ascending=False)
df.head(10)

#### **Part 3: Multiple-column sorting**


Sort the dataframe by:
- Gold medals (descending)
- Silver medals (descending)

In [ ]:
df.sort_values(['Gold Medal', 'Silver Medal'], ascending=False)

Sort the dataframe by:
- Gold (descending)
- Silver (ascending)

In [ ]:
df.sort_values(
    by=['Gold Medal', 'Silver Medal'],
    ascending=[False, True]
)

Sort countries alphabetically, and within each country sort by Total medals (descending).

In [ ]:
df = df.sort_values(
                    by =['Continent', 'Total'], 
                    ascending=[True, False]
                    )

df.head(5)

#### **Part 4: Column-based sorting tricks**


Reorder the dataframe columns so that:
- Country comes first
- Gold, Silver, Bronze, Total come next

In [16]:
order = ['Continent', 'Gold Medal', 'Silver Medal', 'Total']

# Reorder columns
df = df[order + [c for c in df.columns if c not in order]]

df.head(4)

,Continent,Gold Medal,Silver Medal,Total,Team/NOC,Rank by Total,Rank,NOCCode,Bronze Medal
0,North America,39,41,113,United States of America,1,1,USA,33
1,Asia,38,32,88,People's Republic of China,2,2,CHN,18
2,Asia,27,14,58,Japan,5,3,JPN,17
3,Europe,22,21,65,Great Britain,4,4,GBR,22

In [ ]:
cols_ordered = df.columns.get_indexer(order)
df = df.iloc[:, cols_ordered]

df.head(4)

       Continent  Gold Medal  Silver Medal  Total
0  North America          39            41    113
1           Asia          38            32     88
2           Asia          27            14     58
3         Europe          22            21     65

Sort columns alphabetically using axis=1.

In [ ]:
df = df.sort_index(axis=1)
df.head(5)

Move all medal-related columns to the right side of the dataframe.

In [21]:
medal_cols = [c for c in df.columns if any(m in c for m in ['Gold', 'Silver', 'Bronze'])]
other_cols = [c for c in df.columns if c not in medal_cols]

df = df[other_cols + medal_cols]
df.head(5)

       Continent  Total  Gold Medal  Silver Medal
0  North America    113          39            41
1           Asia     88          38            32
2           Asia     58          27            14
3         Europe     65          22            21
4    Europe/Asia     71          20            28

Sort columns by length of column name.

In [ ]:
sorted_cols = sorted(df.columns, key=len, reverse=True)
sorted_cols

df = df[sorted_cols]
df.head()

df = df[sorted(df.columns, key=len, reverse=True)]
df.tail()

Sort columns so that columns containing "Rank" appear first.

In [22]:
rnk = [c for c in df.columns if 'Rank' in c]
print(rnk)
other = [c for c in df.columns if c not in rnk]
print(other)
df = df[rnk + other]
df.head()

[]
['Continent', 'Total', 'Gold Medal', 'Silver Medal']

       Continent  Total  Gold Medal  Silver Medal
0  North America    113          39            41
1           Asia     88          38            32
2           Asia     58          27            14
3         Europe     65          22            21
4    Europe/Asia     71          20            28


Part 5: Challenge tasks 💪


Sort the dataframe by Total medals, but place countries with NaN totals at the bottom.


Sort the dataframe by Gold medals, but break ties using Country name (A → Z).


Sort the dataframe columns based on the sum of their values (largest to smallest).