In [1]:
import pandas as pd

In [ ]:
import pandas as pd

data = {
    'Country': ['USA', 'China', 'Japan', 'Germany', 'India', 'Australia', 'UK'],
    'Gold Medal': [39, 38, 27, 10, 1, 17, 22],
    'Silver Medal': [41, 32, 14, 11, 2, 7, 21],
    'Bronze Medal': [33, 18, 17, 16, 1, 22, 22],
    'Total': [113, 88, 58, 37, 4, 46, 65],
    'Continent': ['America', 'Asia', 'Asia', 'Europe', 'Asia', 'Oceania', 'Europe'],
    'Rank Overall': [1, 2, 3, 4, 5, 6, 7]
}

df = pd.DataFrame(data)

In [24]:
df[:2][:2]

,Country,Gold Medal,Silver Medal,Bronze Medal,Total,Continent,Rank Overall
0,USA,39,41,33,113,America,1
1,China,38,32,18,88,Asia,2

1. Filter rows where Gold Medal > 20

In [26]:
df[df['Gold Medal'] > 20][["Country", "Total", 'Gold Medal']]

  Country  Total  Gold Medal
0     USA    113          39
1   China     88          38
2   Japan     58          27
6      UK     65          22

2. Filter rows where Continent is Asia

In [5]:
df[df['Continent'] == 'Asia']

,Country,Gold Medal,Silver Medal,Bronze Medal,Total,Continent,Rank Overall
1,China,38,32,18,88,Asia,2
2,Japan,27,14,17,58,Asia,3
4,India,1,2,1,4,Asia,5

3. Filter with multiple conditions

In [6]:
df[(df['Gold Medal']> 20) & (df['Country'] == 'USA')]

,Country,Gold Medal,Silver Medal,Bronze Medal,Total,Continent,Rank Overall
0,USA,39,41,33,113,America,1

4. Filter using isin()

In [7]:
df[df['Country'].isin(['USA', 'India','Japan'])]

,Country,Gold Medal,Silver Medal,Bronze Medal,Total,Continent,Rank Overall
0,USA,39,41,33,113,America,1
2,Japan,27,14,17,58,Asia,3
4,India,1,2,1,4,Asia,5

5. Filter using str.contains() (for column with strings)

In [28]:
df = df[df['Country'].str.contains('i', case=False)]
df.head()

,Country,Gold Medal,Silver Medal,Bronze Medal,Total,Continent,Rank Overall
1,China,38,32,18,88,Asia,2
4,India,1,2,1,4,Asia,5
5,Australia,17,7,22,46,Oceania,6

In [9]:
# col = [c for c in df.columns if c.str.contains('Medal', case=False)]
# col

col2 = list(filter(lambda c: 'Medal' in c, df.columns))
col2

['Gold Medal', 'Silver Medal', 'Bronze Medal']

Filter countries not in Asia.

In [10]:
df[df['Country'] != 'Asia']

,Country,Gold Medal,Silver Medal,Bronze Medal,Total,Continent,Rank Overall
0,USA,39,41,33,113,America,1
1,China,38,32,18,88,Asia,2
2,Japan,27,14,17,58,Asia,3
3,Germany,10,11,16,37,Europe,4
4,India,1,2,1,4,Asia,5
5,Australia,17,7,22,46,Oceania,6
6,UK,22,21,22,65,Europe,7

Countries whose name starts with 'J'

In [11]:
df[df['Country'].str.startswith('J')]

,Country,Gold Medal,Silver Medal,Bronze Medal,Total,Continent,Rank Overall
2,Japan,27,14,17,58,Asia,3

Keep only columns with 'Medal' in the name.

In [12]:
medal_col = list(filter(lambda c: 'medal' in c.lower(), df.columns))
medal_col

df[medal_col]

   Gold Medal  Silver Medal  Bronze Medal
0          39            41            33
1          38            32            18
2          27            14            17
3          10            11            16
4           1             2             1
5          17             7            22
6          22            21            22

Drop all columns that contain 'Rank'.

In [13]:
rnk = list(filter(lambda c: 'rank' in c.lower(), df.columns))

df.drop(rnk, axis= 1)

     Country  Gold Medal  Silver Medal  Bronze Medal  Total Continent
0        USA          39            41            33    113   America
1      China          38            32            18     88      Asia
2      Japan          27            14            17     58      Asia
3    Germany          10            11            16     37    Europe
4      India           1             2             1      4      Asia
5  Australia          17             7            22     46   Oceania
6         UK          22            21            22     65    Europe

#### **6️⃣ Using between()**

Countries with Total medals between 50 and 100.

Gold Medals between 10 and 40.

In [14]:
# df[(df['Total'] > 50) & (df['Total'] < 100)]

df[df['Total'].between(30, 100)]

,Country,Gold Medal,Silver Medal,Bronze Medal,Total,Continent,Rank Overall
1,China,38,32,18,88,Asia,2
2,Japan,27,14,17,58,Asia,3
3,Germany,10,11,16,37,Europe,4
5,Australia,17,7,22,46,Oceania,6
6,UK,22,21,22,65,Europe,7

#### **7️⃣ Filtering with query()**

Using string query to filter:

In [15]:
df[:].query('`Gold Medal` > 10 and `Total` > 60' )

,Country,Gold Medal,Silver Medal,Bronze Medal,Total,Continent,Rank Overall
0,USA,39,41,33,113,America,1
1,China,38,32,18,88,Asia,2
6,UK,22,21,22,65,Europe,7

In [29]:
df.iloc[:, :6].query('`Total` > 50')

  Country  Gold Medal  Silver Medal  Bronze Medal  Total Continent
1   China          38            32            18     88      Asia

#### **8️⃣ Filtering index**
- Filter top 3 rows based on index.
- Filter last 2 rows using iloc.

In [40]:
# first 3 rows by index
df[:3]

,Country,Gold Medal,Silver Medal,Bronze Medal,Total,Continent,Rank Overall
1,China,38,32,18,88,Asia,2
4,India,1,2,1,4,Asia,5
5,Australia,17,7,22,46,Oceania,6

In [46]:
# Last 2 rows
df.iloc[-2:]

,Country,Gold Medal,Silver Medal,Bronze Medal,Total,Continent,Rank Overall
4,India,1,2,1,4,Asia,5
5,Australia,17,7,22,46,Oceania,6

#### 9️⃣ **Using apply() for custom filtering**

Filter countries with Total > Gold + Silver.

Filter countries where length of Country name > 5.

In [54]:
df[df['Country'].str.len() > 1]

,Country,Gold Medal,Silver Medal,Bronze Medal,Total,Continent,Rank Overall
1,China,38,32,18,88,Asia,2
4,India,1,2,1,4,Asia,5
5,Australia,17,7,22,46,Oceania,6

In [20]:
filtered_df = df[df['Total'] > (df['Gold Medal'] + df['Silver Medal'])]
filtered_df

,Country,Gold Medal,Silver Medal,Bronze Medal,Total,Continent,Rank Overall
0,USA,39,41,33,113,America,1
1,China,38,32,18,88,Asia,2
2,Japan,27,14,17,58,Asia,3
3,Germany,10,11,16,37,Europe,4
4,India,1,2,1,4,Asia,5
5,Australia,17,7,22,46,Oceania,6
6,UK,22,21,22,65,Europe,7

#### **🔟 Bonus Challenge (Hard)**

Filter countries where Gold > Silver AND Silver > Bronze.

Filter countries whose Total is the max within their Continent (group-wise filter).

In [ ]:
df[(df['Gold Medal'] > df['Silver Medal']) & (df['Silver Medal'] > df['Bronze Medal'])]

,Country,Gold Medal,Silver Medal,Bronze Medal,Total,Continent,Rank Overall
1,China,38,32,18,88,Asia,2

In [56]:
df[df['Total'] == df.groupby('Continent')['Total'].transform('max')]

,Country,Gold Medal,Silver Medal,Bronze Medal,Total,Continent,Rank Overall
1,China,38,32,18,88,Asia,2
5,Australia,17,7,22,46,Oceania,6

In [57]:
df[
    (df['Gold Medal'] > df['Silver Medal']) &
    (df['Silver Medal'] > df['Bronze Medal']) &
    (df['Total'] == df.groupby('Continent')['Total'].transform('max'))
]

,Country,Gold Medal,Silver Medal,Bronze Medal,Total,Continent,Rank Overall
1,China,38,32,18,88,Asia,2