| Feature            | .iloc                          | .loc                           | .at                           |
|--------------------|--------------------------------|---------------------------------|--------------------------------|
| Access type        | Integer position-based         | Label-based                     | Label-based (single value)     |
| Row selection      | Index position (0, 1, 2, ...)  | Index labels                    | Single row label               |
| Column selection  | Column position (0, 1, 2, ...) | Column labels                   | Single column label            |
| Range behavior     | End index **excluded**         | End label **included**          | Not applicable                 |
| Boolean filtering  | ❌ No                           | ✅ Yes                          | ❌ No                          |
| Multiple values    | ✅ Yes                          | ✅ Yes                          | ❌ No                          |
| Single value access| ✅ Yes                          | ✅ Yes                          | ✅ Yes (fastest)               |
| Can set values     | ✅ Yes                          | ✅ Yes                          | ✅ Yes                         |
| Speed              | Fast                           | Slightly slower than iloc       | Fastest (scalar access)        |
| Example            | df.iloc[0, 1]                  | df.loc['USA', 'Gold']           | df.at['USA', 'Gold']           |

In [2]:
import pandas as pd

data = {
    'Country': ['USA', 'China', 'India', 'Germany', 'Australia'],
    'Gold': [39, 38, 28, 10, 17],
    'Silver': [41, 32, 30, 11, 7],
    'Bronze': [33, 18, 25, 16, 22]
}

df = pd.DataFrame(data)

#### 1️⃣ **Using .iloc**

In [3]:
# Select the first row of the DataFrame.
df.iloc[0]

Country    USA
Gold        39
Silver      41
Bronze      33
Name: 0, dtype: object

In [9]:
# Select the Gold medal count for the third country.
cnt = df.iloc[2][['Gold', 'Silver']]
print(cnt)

cnt = df.iloc[2, df.columns.get_loc('Gold')]
print(cnt)

Gold      28
Silver    30
Name: 2, dtype: object
28

In [10]:
# Select all rows and only the Silver and Bronze columns.
df.iloc[:, 2:4]

   Silver  Bronze
0      41      33
1      32      18
2      30      25
3      11      16
4       7      22

#### 2️⃣ **Using .loc**

In [11]:
# Select the row where Country is 'India'.
df.loc[df['Country'] == 'India']


# Select the Gold and Bronze columns for 'Germany'.
df.loc[df['Country'] == 'Germany', ['Gold', 'Bronze']]


# Select rows 1 to 3 and columns Country and Silver.
df.loc[1:3, ['Country', 'Silver']]

   Country  Silver
1    China      32
2    India      30
3  Germany      11

#### 3️⃣ **Using .at**

In [12]:
# Get the Gold medal count for 'Australia'.
print(df.at[4, 'Gold'])

17

In [ ]:
# Update the Bronze medals for 'USA' to 34.
df.at[0, 'Bronze'] = 404


df.head()

     Country  Gold  Silver  Bronze
0        USA    39      41     404
1      China    38      32      18
2      India    28      30      25
3    Germany    10      11      16
4  Australia    17       7      34

**Hints**
- .iloc uses integer positions (df.iloc[row_index, col_index]).
- .loc uses labels (df.loc[row_label, col_label]).
- .at is fast for a single element by label (df.at[row_label, col_label]).

### **1️⃣ Find index of a value in a specific column**

In [46]:
# Example: find the index of 'India' in the Country column
df[df['Country'] == 'India'].index

Index([2], dtype='int64')

In [47]:
# If you want a single index value
df[df['Country'] == 'India'].index[0]

np.int64(2)

In [48]:
# 2️⃣ Using .loc + .index
df.loc[df['Country'] == 'India'].index

Index([2], dtype='int64')

In [13]:
# 3️⃣ Using .idxmax() (for numeric condition)

# Example: country with maximum Gold medals

df['Gold'].idxmax()

0

In [50]:
# 4️⃣ Find index of a value anywhere in the DataFrame
# Using .isin()
df[df.isin(['India'])].stack().index

MultiIndex([(2, 'Country')],
           )

In [ ]:
# 5️⃣ Find index position (integer position)
# If you want the position (not label):

df.index.get_loc(2)          # → position of index label 2

2

In [52]:
# Or:
df['Country'].tolist().index('India')

2

##### ⚠️ **Important Notes**

- `.index` returns **labels**
- `.iloc` works with **positions**
- `.at` / `.iat` are for **single known locations**

---

#### 🧠 **Quick Cheat Sheet**

| Task | Best Method |
|------|------------|
| Index of value in column | `df[df[col] == value].index[0]` |
| Index of max/min value | `idxmax()` / `idxmin()` |
| Position of index | `index.get_loc()` |
| Value anywhere | `isin()` + `stack()` |

---

If you want, I can show how to do this **safely when the value may not exist** (no errors).

##### 🧠 **.iat vs .iloc**

| Method | Supports slicing | Access type | Use case |
|--------|------------------|-------------|----------|
| `.iat` | ❌ No | Integer position | Single value (fastest) |
| `.iloc` | ✅ Yes | Integer position | Rows/columns selection |


##### ✅ **Rule of Thumb**

- **One value** → `.iat`
- **Multiple values / slicing** → `.iloc`