#### **Notes**
- ***as_index=False*** keeps Country as a column instead of index.

In [1]:
import pandas as pd
import numpy as np

data = {
    'Country': ['USA', 'USA', 'China', 'China', 'India', 'India', 'Germany', 'Australia'],
    'Sport': ['Athletics', 'Swimming', 'Athletics', 'Table Tennis',
              'Athletics', 'Hockey', 'Athletics', 'Swimming'],
    'Gold': [10, 12, 8, 5, 6, 4, 3, 7],
    'Silver': [8, 9, 6, 4, 5, 3, 2, 6],
    'Bronze': [7, 6, 5, 3, 4, 2, 1, 5]
}

df = pd.DataFrame(data)
df

     Country         Sport  Gold  Silver  Bronze
0        USA     Athletics    10       8       7
1        USA      Swimming    12       9       6
2      China     Athletics     8       6       5
3      China  Table Tennis     5       4       3
4      India     Athletics     6       5       4
5      India        Hockey     4       3       2
6    Germany     Athletics     3       2       1
7  Australia      Swimming     7       6       5

#### 🧠**Grouping & Aggregation**

In [2]:
# 1️⃣ Basic Grouping

# Group the data by Country
grouped = df.groupby(by='Country')
grouped.sum()

                           Sport  Gold  Silver  Bronze
Country
Australia               Swimming     7       6       5
China      AthleticsTable Tennis    13      10       8
Germany                Athletics     3       2       1
India            AthleticsHockey    10       8       6
USA            AthleticsSwimming    22      17      13

In [3]:
# Calculate the total Gold medals for each country
groupC = df.groupby(by='Country')['Gold'].sum()
groupC


# Option 1: Select column before summing (recommended)
groupC = df.groupby('Country')['Gold'].sum()
groupC

# Option 2: Select column after grouping
groupC = df.groupby('Country').sum()[['Gold']]
groupC

# Option 3: Keep result as DataFrame
groupC = df.groupby('Country', as_index=False)['Gold'].sum()
groupC

     Country  Gold
0  Australia     7
1      China    13
2    Germany     3
3      India    10
4        USA    22

#### 2️⃣ **Multiple Aggregations**

In [4]:
# Group by Country
# Find:   Total Gold      Total Silver    Total Bronze

groupM = df.groupby(by='Country', as_index=False)
groupM.agg('sum')

# Approach 2
df.groupby('Country', as_index=False).sum()

     Country                  Sport  Gold  Silver  Bronze
0  Australia               Swimming     7       6       5
1      China  AthleticsTable Tennis    13      10       8
2    Germany              Athletics     3       2       1
3      India        AthleticsHockey    10       8       6
4        USA      AthleticsSwimming    22      17      13

#### 3️⃣ **Group by Multiple Columns**
- Group by Country and Sport
- Find the sum of all medals

In [5]:
groupM2 = df.groupby(by=['Country', 'Sport']).sum()
groupM2

                        Gold  Silver  Bronze
Country   Sport
Australia Swimming         7       6       5
China     Athletics        8       6       5
          Table Tennis     5       4       3
Germany   Athletics        3       2       1
India     Athletics        6       5       4
          Hockey           4       3       2
USA       Athletics       10       8       7
          Swimming        12       9       6

#### **4️⃣ Different Aggregations per Column**
- Group by Country
- Calculate:
    - Sum of Gold
    - Mean of Silver
    - Max of Bronze

In [6]:
import numpy as np
groupMC = df.groupby(by='Country', as_index=False).agg({
    'Gold':'sum',
    'Silver': 'mean',
    'Bronze':'max'
})

groupMC

     Country  Gold  Silver  Bronze
0  Australia     7     6.0       5
1      China    13     5.0       5
2    Germany     3     2.0       1
3      India    10     4.0       4
4        USA    22     8.5       7

#### 5️⃣ **Using .agg() with Custom Names**
- Group by Country
- Create columns named:
    - Total_Gold
    - Avg_Silver
    - Max_Bronze

In [7]:
# With Alia name
groupMC = df.groupby('Country').agg(
    Total_Gold=('Gold', 'sum'),        # alias: Total_Gold
    Average_Silver=('Silver', 'mean'), # alias: Average_Silver
    Max_Bronze=('Bronze', 'max')       # alias: Max_Bronze
).reset_index()

print(groupMC)

     Country  Total_Gold  Average_Silver  Max_Bronze
0  Australia           7             6.0           5
1      China          13             5.0           5
2    Germany           3             2.0           1
3      India          10             4.0           4
4        USA          22             8.5           7

#### 6️⃣ **Sorting Aggregated Results**
- Group by Country
- Find total medals (Gold + Silver + Bronze)
- Sort countries by highest total medals

In [8]:
df['Total'] = df['Gold'] + df['Silver'] + df['Bronze']

# group_sorted = df.groupby('Country').agg(sum).sort_values('Total', ascending=False)
# group_sorted.head(5)
# # df.head(5)

grouped = df.groupby('Country').sum().reset_index()

group_sorted = grouped.sort_values('Total', ascending=False)

print(group_sorted.head(5))
type(group_sorted)

     Country                  Sport  Gold  Silver  Bronze  Total
4        USA      AthleticsSwimming    22      17      13     52
1      China  AthleticsTable Tennis    13      10       8     31
3      India        AthleticsHockey    10       8       6     24
0  Australia               Swimming     7       6       5     18
2    Germany              Athletics     3       2       1      6

pandas.core.frame.DataFrame

#### 7️⃣ **Filtering Groups**

Show only countries with total Gold medals greater than 10

In [9]:
group_sorted = group_sorted[group_sorted['Total']> 10]
group_sorted

     Country                  Sport  Gold  Silver  Bronze  Total
4        USA      AthleticsSwimming    22      17      13     52
1      China  AthleticsTable Tennis    13      10       8     31
3      India        AthleticsHockey    10       8       6     24
0  Australia               Swimming     7       6       5     18

**8️⃣ Bonus (Advanced)**
- **Group by Sport:** Find which sport has the highest average Gold medals

In [10]:
group_sport = df.groupby('Sport')['Gold'].agg(np.average).reset_index().sort_values('Gold', ascending=False)[:1]
group_sport.head(5)

      Sport  Gold
2  Swimming   9.5

### 💡 **Tips**
- Use .groupby()
- Use .sum(), .mean(), .max()
- Use .agg() for flexibility
- Chain .sort_values() and .reset_index() if needed